### ISSUE TITLE
Improvement: I want to see which argos stabilizer failed so I can troubleshoot failed screenshots

### ISSUE THREAD

**Issue by tommy-anderson** [argos-ci/argos-javascript#133]
## Bug description

Argos has some internal stabilizers

```
waitForNoBusy
waitForImagesToLoad
waitForFontsToLoad
```

sometimes when taking screenshots they fail, and It's very hard to troubleshoot what happened.

### Correct behavior expected

I want to see for that img src=X has not loaded, or that there are 2 elements with aria-busy currently on page.

### Wrong behavior observed
<img width="269" alt="Screenshot 2024-07-01 at 12 41 11 PM" src="https://github.com/argos-ci/argos-javascript/assets/11273582/173f2b56-d507-4944-b654-22b9a07393c6">

Logs are not useful, and need to actually go into node_modules and add console messages to debug.

## Reproduce
Have a image with a bad src in the page you're trying to screenshot. And screenshot it.

## Notes

I wanted to open a PR where I would just add the `errorMsg` property to the `waitUntil` call, but since you currently have everything in a single function `waitForStability` the change would involve modifying the way stabilization is done, and would be too opinionated.

**Comment by gregberge** [comment]
Hello @tommy-anderson, yeah it would definitely be a good improvement. What we would do is another function to get some debug information: "what caused `waitForStability`" to not wait. So we could call this function in the error message to get debug information. What do you think?

**Comment by tommy-anderson** [comment]
Sure that could work !
