### ISSUE TITLE
[Question] - The build is always an orphan build

### ISSUE THREAD

**Issue by kobenguyent** [argos-ci/argos-javascript#149]
Maybe I don't understand much how to configure properly but the build is always an orphan build without any baseline

![Screenshot 2024-09-06 at 14 31 06](https://github.com/user-attachments/assets/31993ec9-3575-43d9-8a51-f16c4c9c4bca)

I created a PR from the main branch, I updated the test to take new screenshot, argosCI is triggered but it is an orphan build.

More info:
https://github.com/kobenguyent/codeceptjs-ArgosCIHelper/pull/2

**Comment by gregberge** [comment]
Hey @kobenguyent, the reason could be that your branch is not rebased.

**Comment by jsfez** [comment]
Hi @kobenguyent,
I’m one of the Argos maintainers. [Let’s schedule a quick call](https://cal.com/jsfez) to help you with the setup. I’ll walk you through everything to get you up and running smoothly.
