### ISSUE TITLE
Configurable comparison threshold

### ISSUE THREAD

**Issue by jsfez** [argos-ci/argos-javascript#38]
We will allow to specify a custom preconfigured threshold value for a specific screenshot in the UI. 

+ Add a page about what is Argos diffing strategy.

**Comment by canalun** [comment]
Hi, I'm a user of argos-ci. Thank you for developing this great application :)

I'm now facing with the threshold problem (some differences of color are not detected by argos-ci.com),
and could I ask you two quick question?

1. Is this threshold feature planned to be supported as an option on argos-ci.com?
2. Currently, is there any workaround for color threshold problem?(now, I take and upload snapshots by @argos-ci/cli and check the result on argos-ci.com.)

**Comment by gregberge** [comment]
Hi @canalun, sorry for the answer delay. I think we could make it configurable, for some use cases it could make sense.

Could you send me a link of a broken build so I can check and experiment with it?

**Comment by canalun** [comment]
Hi @gregberge , sorry for the late reply...!

Thank you for considering the idea.
Unfortunately, I've lost the URL. But I have the original two images argos compared, and is it enough to share them??(if not, please tell me!!)

The problem with these two images is that argos did not detect the difference of 2 cells at the lower left corner, that is, "red" and "yellow" of "pale" row.
Actually, the all 10 colored cells had been changed and argos detected the difference of all other 8 cells.

I tried to compare the two images using odiff-bin with the threshold argos uses, and, of course, the result was the same. I've not tried with different threshold yet.

<img width="389" alt="スクリーンショット 2023-11-06 16 23 54" src="https://github.com/argos-ci/argos-javascript/assets/61643630/40f90bd6-e53b-4c88-8a48-854cb6c6067b">

<img width="594" alt="スクリーンショット 2023-11-06 16 24 14" src="https://github.com/argos-ci/argos-javascript/assets/61643630/9d59f37f-1e10-4789-a5c7-4138f7061dda">

**Comment by gregberge** [comment]
We have improved our algorithm to detect color changes. See #1153
