### ISSUE TITLE
Bug: Cypress screenshot does not work

### ISSUE THREAD

**Issue by samtsai** [argos-ci/argos-javascript#73]
## Bug description

Timed out retrying after 4000ms: cy.readFile("node_modules/@argos-ci/browser/dist/global.js") failed because the file does not exist at the following path:
<CODE_PATH>/node_modules/@argos-ci/browser/dist/global.js

### Correct behavior expected

`cy.argosScreenshot()` should work and find any dependent files.

### Wrong behavior observed

File dependency is missing or there is an installation step missing from documentation.

### Screenshot

<img width="337" alt="Screenshot 2023-10-24 at 10 12 43 AM" src="https://github.com/argos-ci/argos-javascript/assets/225526/2f1b089f-4fb1-4875-ac30-4a2665b98ac3">

## Reproduce

Follow https://argos-ci.com/docs/cypress

## Setup

Browser: Chrome
Package manager: pnpm 8.9.2
Node: 20.8.0
Cypress: 13.3.2

**Comment by samtsai** [comment]
This is resolved if you install `@argos-ci/browser`

**Comment by gregberge** [comment]
@samtsai `@argos-ci/browser` is already a dependency of `@argos-ci/cypress`, see https://www.npmjs.com/package/@argos-ci/cypress?activeTab=dependencies

It looks like it was a installation issue... You should not have to install `@argos-ci/browser` by yourself.

**Comment by samtsai** [comment]
However, for me I can install it manually (won't take up more space I don't think)

Also, I've opened this:
https://github.com/argos-ci/argos-javascript/pull/74

**Comment by gregberge** [comment]
@samtsai the origin of the bug is that `require.resolve` is not available. Could you please give me your configuration so I can check when it is not available and try to find another solution?

**Comment by gregberge** [comment]
Fixed in #74
