### ISSUE TITLE
Remove sticky before fullpage screenshot

### ISSUE THREAD

**Issue by jsfez** [argos-ci/argos-javascript#84]
## Issue
A lot a our users have a issue with sticky navbar that happen when they try to screenshot a fullpage. 

1. I suggest that we enforce `display: relative` on all sticly items before taking a fullpage screenshot by default. 

2. I recommend to allow to deactive this behavior with a `--allow-sticky` option.

**Comment by gregberge** [comment]
Fixed in latest release. https://github.com/argos-ci/argos-javascript/pull/86
